- tags: kde
  block:

    - name: kde - install Plasma and Plasma applications
      become: true
      community.general.pacman:
        name: 
          - plasma-meta
          - kde-applications-meta
          - sddm-kcm
        state: present

    - name: kde - install helpful Plasma add-ons
      # https://community.kde.org/Distributions/Packaging_Recommendations
      community.general.pacman:
        name: 
          - ffmpegthumbs
          - dolphin-plugins
          - kdegraphics-thumbnailers
          - kdenetwork-filesharing
        state: present
