- tags: kde
  block:

    - name: install KDE and KDE apps
      become: true
      community.general.pacman:
        name: 
          - plasma-meta
          - kde-applications-meta
          - sddm-kcm
          - audacious
          - plasmay-wayland-session
        state: present
