- tags: alacritty
  block:

    - name: alacritty - Install packages
      become: true
      community.general.pacman:
        state: latest
        name:
          - alacritty  # A cross-platform, GPU-accelerated terminal emulator

    - name: Create config files
      block:
      - name: alacritty - Create directories
        ansible.builtin.file:
          path: "{{ home }}/.config/alacritty"
          owner: "{{ user }}"
          group: "{{ user }}"
          mode: '700'
          state: directory

      - name: alacritty - Create links
        ansible.builtin.file:
          src: "{{ repo_dir }}/config/alacritty/files/{{ item.name }}"
          path: "{{ home }}/.config/alacritty/{{ item.name }}"
          owner: "{{ user }}"
          group: "{{ user }}"
          mode: '{{ item.mode }}'
          state: "link"
        loop:
          - { name: "alacritty.toml", mode: "600" }
          # link the entire theme directory, that way you can add and delete themes whenever you want without the need to edit this file
          - { name: "themes", mode: "700" }

