# Configuration docs: https://alacritty.org/config-alacritty.html

import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

[env]
# (this is required in order to correctly display the colors in tmux)
TERM = "xterm-256color"

[font]
size = 10
normal = { family = "monospace-double", style = "Regular" }
bold = { style = "Bold" }
bold_italic = { style = "Bold Italic" }
italic = { style = "Italic" }

[scrolling]
multiplier = 1

[window]
dynamic_padding = true
