# must be `all` and not `localhost` to be able to get the {{inventory_hostname}} value
- hosts: localhost

  # TODO
  # fnm
  # pnpm
  # hexchat
  # obsidian
  # vscode
  # wezterm
  # pyenv
  roles:
    # core system setup
    - pre_install
    - pacman
    - zsh
    - yay
    - common
    - system
    - kde
    - wayland
    - bluetooth
    - fonts
    - stow

    # applications
    - mpv
    