# must be `all` and not `localhost` to be able to get the {{inventory_hostname}} value
- hosts: localhost
  # tasks:


  #   - import_tasks: config/no_config/main.yml       # must go after pacman and paru

  #   - import_tasks: config/bluetooth/main.yml

  #   - import_tasks: config/starship/main.yml
  #   # - import_tasks: config/ssh/main.yml
  #   - import_tasks: config/git/main.yml

  #   - import_tasks: config/nvim/main.yml

  #   - import_tasks: config/hypr/main.yml
  #   - import_tasks: config/dunst/main.yml
  #   - import_tasks: config/swaylock/main.yml
  #   - import_tasks: config/tofi/main.yml
  #   - import_tasks: config/waybar/main.yml

  #   #- import_tasks: config/wallpaper/main.yml       # must go after ssh

  #   #- import_tasks: config/fonts/main.yml           # must go after ssh
  #   #- import_tasks: config/fontconfig/main.yml
  #   #- import_tasks: config/fontpreview/main.yml

  #   - import_tasks: config/mpv/main.yml

  #   #- import_tasks: config/spotify/main.yml

    # TODO
    # fnm
    # pnpm
    # cpu-x
    # hexchat
    # obsidian
    # vscode
    # wezterm
    # pyenv
  roles:
    - pre_install
    - pacman
    - zsh
    - yay
    - common
    - system
    - bluetooth
    - dunst
    - mpv
    - kde