- tags: paru
  block:

    - name: paru - Ensure `base-devel` is installed
      # Should be already installed, but just in case someone does not read the README.md file
      become: true
      community.general.pacman:
        state: latest
        name: base-devel

    - name: paru - Check if paru already installed
      ansible.builtin.command: "which paru"
      register: which_paru
      ignore_errors: true

    - name: Install paru
      # https://github.com/Morganamilo/paru?tab=readme-ov-file#installation
      # Once installed this will never run again, update paru with paru itself
      when: which_paru.rc != 0
      block: 

      - name: paru - Clone the `paru` repository
        ansible.builtin.git:
          repo: https://aur.archlinux.org/paru.git
          dest: "/tmp/paru/"

      - name: paru - Build
        # `-s` installs dependencies automatilly
        # `-i` install the package after successfully building it
        # `--noconfirm` answers `yes` to all prompts without asking questions
        ansible.builtin.shell: "cd /tmp/paru && makepkg -si --noconfirm"

