- tags: wayland
  block:

    - name: wayland - install wayland
      become: true
      community.general.pacman:
        name: 
          - wayland
          - xorg-xwayland
          - xorg-xlsclients
          - qt5-wayland
          - glfw-wayland
        state: present