# ------------------------------------------------------------------------------
#             
#               _____                    _       _         _
#              |_   _|__ _ __ ___  _ __ | | __ _| |_ ___  | |
#                | |/ _ \ '_ ` _ \| '_ \| |/ _` | __/ _ \ | |
#                | |  __/ | | | | | |_) | | (_| | ||  __/ |_|
#                |_|\___|_| |_| |_| .__/|_|\__,_|\__\___| (_)
#                                 |_|
#             
# ------------------------------------------------------------------------------

# Configuration
#   https://github.com/hrkfdn/ncspot/blob/main/doc/users.md#configuration

use_nerdfont = true
flip_status_indicators = true
# notify = true

#-------------------------------------------------------------------------------

# Custom keybindings
#   https://github.com/hrkfdn/ncspot/blob/main/doc/users.md#custom-keybindings

[keybindings]
# disable quitting (use `:quit`)
"q" = "noop"
# remapings
"Ctrl+q" = "focus queue"
"Ctrl+f" = "focus search"
"Ctrl+l" = "focus library"
"Ctrl+h" = "focus library"
"Ctrl+n" = "next"
"Ctrl+p" = "previous"
# easier play/pause
"Space" = "playpause"
"Esc" = "back"

#-------------------------------------------------------------------------------

# Custom theme
#   https://github.com/hrkfdn/ncspot/blob/main/doc/users.md#theming

[theme]
background = "{{ color_black }}"
primary = "{{ color_white_high }}"
secondary = "{{ color_white_high }}"
title = "{{ color_white_high }}"
playing = "{{ color_green }}"
playing_selected = "{{ color_white_high }}"
playing_bg = "{{ color_highlight_low }}"
highlight = "{{ color_white_high }}"
highlight_bg = "{{ color_green }}"
error = "{{ color_red }}"
error_bg = "{{ color_black_low }}"
statusbar = "{{ color_white_high }}"
statusbar_progress = "{{ color_green }}"
statusbar_bg = "{{ color_black_low }}"
cmdline = "{{ color_yellow }}"
cmdline_bg = "{{ color_black_low }}"

