- tags: fonts
  block:
    # I cannot include proprietary fonts in a public repo, all fonts should 
    # be stored in a private repository.
    - name: fonts - Clone the fonts private repository
      ansible.builtin.git:
        repo: "git@github.com:mabq/fonts.git"
        dest: "{{ home }}/projects/fonts"
        clone: true
        update: true
        key_file: "{{ home }}/.ssh/{{ ssh_key_name }}"
        # This is the first time connecting to github via ssh, we must 
        # accept it's key to be automatically added to the `known_hosts`
        # file, otherwise the verification fails.
        accept_hostkey: true

    - name: fonts - Create link to the `fonts` directory
      become: true
      ansible.builtin.file:
        src: "{{ home }}/projects/fonts/fonts"
        path: "/usr/local/share/fonts"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '755'
        state: "link"

