- tags: zsh
  block:

    - name: zsh - Install packages
      become: true
      community.general.pacman:
        state: latest
        name:
          - zsh                             # A very advanced and programmable command interpreter (shell) for UNIX
          - zsh-autosuggestions             # Fish-like autosuggestions for zsh
          - zsh-history-substring-search    # ZSH port of Fish history search (up arrow)
          - zsh-syntax-highlighting         # Fish shell like syntax highlighting for Zsh

    - name: zsh - Make it the user's default shell
      become: true
      ansible.builtin.user:
        name: "{{ user }}"
        shell: /usr/bin/zsh

