- tags: git 
  block:

    - name: git - Install packages
      become: true
      community.general.pacman:
        state: latest
        name:
          - git             # The fast distributed version control system
          - git-delta       # Syntax-highlighting pager for git and diff output

    - name: git - Create links
      ansible.builtin.file:
        src: "{{ repo_dir }}/config/git/files/{{ item.name }}"
        path: "{{ home }}/{{ item.name }}"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '600'
        state: "link"
      loop:
        - { name: ".gitconfig" }
