- tags: noconfig
  block:

    - name: no-config - Install packages that do not require configuration files from official repositories
      become: true
      community.general.pacman:
        state: latest
        name:
          # ------------------------------------------------------------------------
          #
          # Core utilities alternatives:
          - bat                 # Cat clone with syntax highlighting and git integration (`cat` alternative)
          - eza                 # Modern replacement for ls, community fork of exa (`ls` alternative)
          - fd                  # Simple, fast and user-friendly alternative to find (`find` alternative)
          - fzf                 # Command-line fuzzy finder
          - rsync               # A fast and versatile file copying tool for remote and local files (`cp` alternative)
          - trash-cli           # Command line trashcan (recycle bin) interface (`rm` alternative)
          - zoxide              # A smarter cd command for your terminal (`cd` alternative)
          #
          # ------------------------------------------------------------------------
          #
          # Ansible:
          - sshpass             # Fool ssh into accepting an interactive password non-interactively (required by Ansible to run playbooks on remote managed nodes, in case you ever use this computer to run the `arch-base` playbook on another computer)
          #
          # ------------------------------------------------------------------------
          #
          # Help utilities:
          - man-db              # A utility for reading man pages 
          - man-pages           # Linux man pages
          - tldr                # Command line client for tldr, a collection of simplified and community-driven man pages
          #
          # ------------------------------------------------------------------------
          #
          # System monitor utilities:
          - bottom              # A graphical process/system monitor (`htop` alternative)
          - hwinfo              # Hardware detection tool from openSUSE
          - neofetch            # A CLI system information tool written in BASH that supports displaying images.
          #
          # ------------------------------------------------------------------------
          #
          # Disk utilities:
          - duf                 # Disk Usage/Free Utility (`df` alternative)
          - ncdu                # Disk usage analyzer like WinDirStat (`du` alternative)
          #
          # ------------------------------------------------------------------------
          #
          # Filesystem utilities:
          - dosfstools          # DOS filesystem utilities
          - exfat-utils         # Utilities for exFAT file system
          - mtools              # A collection of utilities to access MS-DOS disks
          #
          # ------------------------------------------------------------------------
          #
          # Compression/Uncompression utilities (used by zsh custom function `extract`):
          - p7zip               # Command-line file archiver with high compression ratio
          - unarchiver          # unar and lsar: Objective-C tools for uncompressing archive files 
          - unrar               # The RAR uncompression program
          - unzip               # For extracting and viewing files in .zip archives
          - zip                 # Compressor/archiver for creating and modifying zipfiles
          #
          # ------------------------------------------------------------------------
          #
          # Network utilities:
          # - bind-tools          # A complete, highly portable implementation of the DNS protocol
          # - nfs-utils           # Support programs for Network File Systems
          # - whois               # Intelligent WHOIS client
          - bandwhich           # Terminal bandwidth utilization tool
          - ethtool             # Utility for controlling network drivers and hardware
          - traceroute          # Tracks the route taken by packets over an IP network
          - wget                # Network utility to retrieve files from the Web (used by Neovim to download files on the internet when pressing `gf`)
          - speedtest-cli       # Command line interface for testing internet bandwidth using speedtest.net
          #
          # ------------------------------------------------------------------------
          #
          # Firewalls and ports:
          - nmap                # Utility for network discovery and security auditing (great to check open ports)
          #
          # ------------------------------------------------------------------------
          #
          # Audio:
          - pipewire-alsa       # Low-latency audio/video router and processor - ALSA configuration
          - pipewire-jack       # Low-latency audio/video router and processor - JACK replacement
          - pipewire-pulse      # Low-latency audio/video router and processor - PulseAudio replacement
          - pavucontrol         # PulseAudio Volume Control
          #
          # ------------------------------------------------------------------------
          #
          # Images:
          - nsxiv               # Neo (or New or Not) Simple (or Small or Suckless) X Image Viewer
          #
          # ------------------------------------------------------------------------
          #
          # Fonts:
          - noto-fonts-emoji    # Google Noto emoji fonts
          #
          # ------------------------------------------------------------------------
          #
          # Browsers:
          - chromium            # A web browser built for speed, simplicity, and security
          - firefox             # Standalone web browser from mozilla.org
          #
          # ------------------------------------------------------------------------
          #
          # Torrents:
          - qbittorrent         # An advanced BitTorrent client programmed in C++, based on Qt toolkit and libtorrent-rasterbar
          #
          # ------------------------------------------------------------------------
          #
          # Books:
          - evince              # Document viewer (PDF, PostScript, XPS, djvu, dvi, tiff, cbr, cbz, cb7, cbt)
          - foliate             # A simple and modern GTK eBook reader
          - mdbook              # Create book from markdown files, like Gitbook but implemented in Rust
          #
          # ------------------------------------------------------------------------
          #
          # Office:
          - libreoffice-fresh   # LibreOffice branch which contains new features and program enhancements
          #
          # ------------------------------------------------------------------------
          #
          # Other utils:
          - stow                # Manage installation of multiple software in the same directory tree
          #
          # ------------------------------------------------------------------------
          #
          # Programming:
          - hyperfine           # A command-line benchmarking tool
          - jq                  # Command-line JSON processor
          # - go
          # - nodejs
          # - npm
          # - shellcheck
          #
          # ------------------------------------------------------------------------

