- tags: firefox
  block:

    - name: Install firefox
      tags: aur
      # Note: firefox sync code is stored in the passwords database (enter it manually after installation)
      block:
        - name: firefox - Check if firefox is already installed
          ansible.builtin.command: "which firefox"
          register: which_firefox
          ignore_errors: true

        - name: firefox - Install firefox
          when: which_firefox.rc != 0
          # Web browser that blocks ads and trackers by default (binary release)
          ansible.builtin.shell: 'yay -S --skipreview firefox-bin'
